# Generated by Django 4.2.5 on 2023-11-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenName', models.CharField(max_length=200)),
                ('artName', models.CharField(max_length=200)),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('paidAmount', models.FloatField()),
            ],
        ),
    ]
