# Generated by Django 4.2.5 on 2023-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_artwork_imagepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
